energy_pipeline:
  target: local
  outputs:
    local:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | as_number }}"
      user: "{{ env_var('POSTGRES_USER', 'dakota') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'dakota') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'energy') }}"
      schema: staging
      threads: 4
