"""Executive report asset: depends on the gold marts, produces the PDF."""

from dagster import AssetExecutionContext, AssetKey, MaterializeResult, asset


@asset(
    group_name="reporting",
    # Two-part AssetKeys match dbt model schemas generated by DagsterDbtTranslator
    deps=[
        AssetKey(["marts", "agg_daily_region_summary"]),
        AssetKey(["marts", "fct_generation_hourly"]),
    ],
    kinds={"python"},
)
def executive_report(context: AssetExecutionContext) -> MaterializeResult:
    from reports.generate_report import build_report  # deferred: keeps weasyprint out of import path for tests

    pdf_path, period = build_report()
    context.log.info(f"report written: {pdf_path}")
    return MaterializeResult(
        metadata={"pdf_path": str(pdf_path), "report_period": period}
    )
